#!/bin/bash
# Installation: ln -s ../../precommit-hook.sh .git/hooks/pre-commit

git diff --cached --name-status | while read status file; do
	if [[ "$file" =~ ^patches/ ]] || [[ "$file" =~ ^debian/tools/ ]]; then
		echo ""
		echo "*** UPDATING AUTOGENERATED FILES ***"
		echo ""
		debian/tools/patchupdate.py > patches/Makefile || exit 1
		git add patches/Makefile || exit 1
		break;
	fi
done
