#!/bin/sh -e

if [ "$1" = "upgrade" ] ; then
	if ps -C wineserver > /dev/null && test -d /var/lib/update-notifier/user.d/ ; then
		cp -f /usr/share/wine/wineserver-restart-required.update-notifier /var/lib/update-notifier/user.d/wineserver-restart-required
	fi
fi

service procps start || /etc/init.d/procps restart

# Automatically added by dh_installmime
if [ "$1" = "configure" ] && [ -x "`which update-mime 2>/dev/null`" ]; then
	update-mime
fi
# End automatically added section
# Automatically added by dh_makeshlibs
if [ "$1" = "configure" ]; then
	ldconfig
fi
# End automatically added section



